FROM ubuntu:latest

RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends \
    apt-transport-https \
    apt-utils \
    ca-certificates \
    curl \
    git \
    iputils-ping \
    jq \
    lsb-release \
    software-properties-common \
    wget

RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Powershell

# Update the list of packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update

# Install pre-requisite packages.
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y wget

# Download the PowerShell package file
RUN DEBIAN_FRONTEND=wget https://github.com/PowerShell/PowerShell/releases/download/v7.4.4/powershell_7.4.4-1.deb_amd64.deb

###################################
# Install the PowerShell package
RUN DEBIAN_FRONTEND=dpkg -i powershell_7.4.4-1.deb_amd64.deb

# Resolve missing dependencies and finish the install (if necessary)
RUN DEBIAN_FRONTEND=apt-get install -f

# # Delete the downloaded package file
# RUN DEBIAN_FRONTEND=rm powershell_7.4.4-1.deb_amd64.deb

# # Install Azure Powershell
# RUN pwsh -Command "Install-Module -Name Az -Force -AllowClobber -Scope AllUsers"


# Can be 'linux-x64', 'linux-arm64', 'linux-arm', 'rhel.6-x64'.
ENV TARGETARCH=linux-x64

WORKDIR /azp

COPY azure-pipelines-agent/start.sh .
RUN chmod +x start.sh

ENTRYPOINT [ "./start.sh" ]